name: flutter_base
description: "A Base Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_core:
    path: packages/app_core
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  go_router: ^14.8.1
  get_it: ^8.0.3
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  # class_name: S # Optional. Name for the generated localization class. Default: S
  # main_locale: en # Optional. The main locale for your app. Default: en
  # arb_dir: lib/l10n # Optional. Directory containing ARB files. Default: lib/l10n
  # output_dir: lib/generated # Optional. Directory for generated Dart localization files. Default: lib/generated
  # use_deferred_loading: false # Optional. Whether to use deferred loading for the generated localization files. Default: false
  # generate_timestamp: true # Optional. Appends timestamp to the generated files. Default: false
  # localizely:
  #   project_id: <YOUR_PROJECT_ID> # Optional. Localizely project ID for integrations

